version: '2'
services:
 uvadddpus: 
  image: semanticwebcompany/uv-add-dpus:latest
  volumes_from:
    - uvshared
  links:
    - uvfrontend:frontend
 uvfrontend:
  image: semanticwebcompany/unifiedviews-frontend:latest
  restart: always
  ports:
    - "8088:8080"
#  volumes:
##    - /etc/timezone:/etc/timezone:ro
##    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - uvshared
  links:
    - uvdb:mysql
    - uvbackend:uvbackend
 uvbackend:
  image: semanticwebcompany/unifiedviews-backend:latest
  restart: always
  ports:
    - "8076:8066"
  volumes:
    - ./data/unified-views/tmp:/tmp
#    - /etc/timezone:/etc/timezone:ro    
#    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - uvshared
  links:
    - uvdb:mysql
 uvdb:
  image: semanticwebcompany/uv-mariadb:latest
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: "UV"
    MYSQL_PASSWORD: "UV"
  volumes:
    - ./data/mysql:/var/lib/mysql
#    - /etc/timezone:/etc/timezone:ro
#    - /etc/localtime:/etc/localtime:ro

 uvshared:
  image: semanticwebcompany/unifiedviews-shared:latest
  environment:
    UV_DATABASE_SQL_PASSWORD: "UV"
  volumes:
    - ./data/unified-views/logs:/unified-views/logs
    - ./data/unified-views/config:/unified-views/config
    - ./data/unified-views/backend:/unified-views/backend
